### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by ghost** [stainley/jammming#1]
There's a few changes that need to be made just to get the search functionality to work.

1. Your Spotify module is not properly authenticating the Spotify API. 

https://github.com/stainley/jammming/blob/master/src/util/Spotify.js#L19

Use `window.location` instead of `window.location.href` to redirect your browser to the Spotify auth page.

2. You need to actually call the Spotify.search() from your App component.

https://github.com/stainley/jammming/blob/master/src/Components/App/App.js#L85-L87

Call Spotify.search() here instead of just printing out the search term.

3. Your SearchBar component should call the `this.props.onSearch()` method using the current search term.

https://github.com/stainley/jammming/blob/master/src/Components/SearchBar/SearchBar.js#L14-L16

The search term exists in state. Use `this.state.term` to refer to that term, the term is not actually being passed as a parameter.

4. Your SearchBar component needs to call its search method when the the `a` tag gets clicked.

https://github.com/stainley/jammming/blob/master/src/Components/SearchBar/SearchBar.js#L28

Use an `onClick` event handler.

**Comment by stainley** [comment]
Thank you!, I didn't see the task #88, was my bad 👍I did it.
